### PR TITLE
Written code for 'Swapping Two Numbers' functionality and commiting to

### PR DESCRIPTION
**Pull request by testingprof1**
Hi Lead,
I added code for Swapping_Two_Numbers functionality. Please review.

Thanks,
Tester1

### CODE REVIEW

**Comment by mysharedrepository** [comment]
Hi Tester,
Perform same functionality in different ways.

Thanks,
Lead

**Comment by testingprof1** [comment]
Hi Lead,
I have changed input values.

Thanks,
Tester

**Comment by mysharedrepository** [comment]
Hi Tester,
Change input values one more time.

Thanks,
Lead

**Comment by testingprof1** [comment]
Hi Lead,
Changed input values one more time. Please review

Thanks,
Tester

**Comment by mysharedrepository** [comment]
Hi Tester,
Your code looks good. Please go head with merge to master branch.

Thanks,
Lead

**Pull request merged**
